# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-25 17:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('temporary_tent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permanent_tent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('men_pants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('women_pants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('men_shirt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('women_shirt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('men_shoes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('women_shoes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_shoes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_pants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carpet', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blanket', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('canned_food', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compote_and_juice', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('helicopter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ambulance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firefighter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doctor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nurse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('police', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('voluntry_manpower', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crane', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('excavator', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bulldozer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('truck', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grinder', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('electric_hammer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('electrik_driller', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('welding_engine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gas_welding', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shovel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pocket', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hammer', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
