# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-30 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='unit',
        ),
    ]
