# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webgis.Unit'),
        ),
    ]
